Marketplace
ASCIT/donut pull request #103
Opened 2019-11-13 01:02 UTC by calebsander

### Summary
- Finish marketplace
- Remove SQLAlchemy
- Add tests for marketplace

### Test Plan
- Pretty extensive tests
- Tried adding items, editing items, and searching

2019-11-13 07:19 UTC, koivyr requested changes
1. Super nitpick but a lot of the python comments have lowercased first word when they should be capitalized. 
2. What we talked today -- hid listings when people aren't logged in. (Will need to do with directory and viewing user data too). 
3. Also what we talked about but can be moved to a future fix-- the market place bar is taking up literally the page so people have to scroll quite far to do anything. @Thought-Weaver our residential designer? 
4. lol @ categories abc def
5. ty for this!!

2019-11-13 07:19 UTC, koivyr commented on donut/modules/marketplace/helpers.py
> +                 'item_timestamp', 'cat_title', 'item_active')
Move the constants to the top?

2019-11-13 07:19 UTC, koivyr commented on donut/modules/marketplace/templates/sell.html
> +            {% for textbook in textbooks %}
I'd limit this lol otherwise it'll get loooonnngggg

2019-11-13 07:19 UTC, koivyr commented on donut/modules/marketplace/templates/marketplace.html
> +    <div class="faq-q">Why are all the images hosted in Imgur?</div>
Missed a <li></li> here.

2019-11-13 07:19 UTC, koivyr commented on donut/static/js/marketplace/sell_images.js
> +      console.log(response);
get rid of console log?

2019-11-13 07:19 UTC, koivyr commented on donut/static/js/marketplace/sell_images.js
> +  );
Is there a reason why we are generating this with JS instead of coding it up with just html..?

2019-11-14 01:05 UTC, Wingfril commented on donut/static/js/marketplace/sell_images.js
> +}
Make a note somewhere that you can't upload images greater than 10 mb

2019-11-28 02:09 UTC, calebsander commented on donut/static/js/marketplace/sell_images.js
> +  );
Presumably so the click handler can capture the `imageNum` variable? IDK, if it works I don't really want to change it

2019-12-04 00:27 UTC, koivyr approved these changes

2019-12-04 01:57 UTC, merged