Insert perm
ASCIT/donut pull request #138
Opened 2020-03-05 09:57 UTC by Wingfril

### Summary
- (This is stacked on my other commit)
- Permissions. 

### Test Plan
- Go into the db lol

2020-03-07 22:04 UTC, rlin0 commented on donut/modules/groups/utils/position_importer.py
> +    return res
`return res['group_id']`

2020-03-07 22:04 UTC, rlin0 commented on donut/modules/groups/utils/position_importer.py
> +    return res
`return None if res is None else res['pos_id']`

2020-03-07 22:04 UTC, rlin0 commented on donut/modules/groups/utils/position_importer.py
> +        res = get_group_id(group_name, db)
I think you can use `cursor.lastrowid` to get the last inserted id

2020-03-07 22:04 UTC, rlin0 commented on donut/modules/groups/utils/position_importer.py
> +        res = get_position_id(pos_name, group_id, db)
same here `cursor.lastrowid`?

2020-03-09 23:43 UTC, calebsander requested changes

2020-03-09 23:43 UTC, calebsander commented on donut/modules/groups/utils/insert_permissions.py
> +        False: [1] # All
`True` means they have control privileges? Would be good to comment this

2020-03-09 23:43 UTC, calebsander commented on donut/modules/groups/utils/insert_permissions.py
> +        True: [2, 4, 5], #Edit Rotation Info, Editing Pages, Upload documents
Would be clearer to import the permissions enums and use the named values instead of these magic numbers. But not a big issue if that seems like too much work

2020-03-09 23:43 UTC, calebsander commented on donut/modules/groups/utils/insert_permissions.py
> +        True: [2, 4, 5], #Edit Rotation Info, Editing Pages, Upload documents
I also removed permission 2; it's not used anywhere in the code

2020-03-09 23:43 UTC, calebsander commented on donut/modules/groups/utils/insert_permissions.py
> +        for group in valid_permissions:
Might be a little cleaner to iterate over `group, group_permissions in valid_permissions.items()`. Ditto for `control, control_permissions in group_permissions.items()`

2020-03-09 23:43 UTC, calebsander commented on donut/modules/groups/utils/position_importer.py
> +import argparse
Rebase pls

2020-03-10 05:33 UTC, calebsander commented on donut/modules/groups/utils/insert_permissions.py
> +
Missing survey perm?

2020-03-10 05:38 UTC, Wingfril commented on donut/modules/groups/utils/insert_permissions.py
> +
yikes woops

2020-03-10 06:08 UTC, calebsander approved these changes

2020-03-10 06:17 UTC, merged