arc feature requests
ASCIT/donut pull request #176
Opened 2020-05-15 08:01 UTC by rlin0

### Summary
- arc's feature requests

### Test Plan
- testing posting feedbacks

2020-05-15 08:04 UTC, rlin0 commented on donut/modules/feedback/routes.py
> +# Remove an email from this complaint
forgot to edit function description

2020-05-17 19:08 UTC, calebsander requested changes

2020-05-17 19:08 UTC, calebsander commented on donut/modules/feedback/templates/complaint.html
> +				<label><input type="radio" name="ombuds" value=0 onchange="this.form.submit()" {% if not complaint['ombuds'] %} checked {% endif %}>No</label>
Might be simpler as a single checkbox

2020-05-17 19:08 UTC, calebsander commented on donut/modules/feedback/routes.py
> +    if 'username' not in flask.session or group != 'arc':
Would be better to put `arc` in the route instead of `<group>`, since a 404 is a more appropriate error than a 403 if the group is incorrect

2020-05-17 19:08 UTC, calebsander commented on donut/modules/feedback/templates/feedback.html
> +			  <label><input type="radio" name="ombuds" value=0>No</label>
Ditto about using a checkbox here. At the very least, these inputs should be marked as `required`.

2020-05-17 19:08 UTC, calebsander commented on donut/modules/newsgroups/helpers.py
> +            AND (control = 1 OR send = 1)
I don't think we should be special-casing this; `control` and `send` mean separate things. What was the reason for doing this?

2020-05-17 21:50 UTC, calebsander submitted a review, later dismissed

2020-05-17 21:50 UTC, calebsander commented on donut/modules/feedback/helpers.py
> +    returns False if complaint_id is invalid
Ah oops I missed this but I think this docstring describes a different function

2020-05-20 18:11 UTC, calebsander commented
@rlin0 lgtm; I just adjusted the form styling so that the inputs aren't squished to the right on the ARC feedback page (due to the longer label). If this looks okay to you, I approve the merge.

2020-05-20 22:48 UTC, merged