Room reservations
ASCIT/donut pull request #63
Opened 2018-02-02 01:40 UTC by calebsander

### Summary
- Added room reservations

### Test Plan
- Try booking some rooms; make sure conflicts are checked correctly
- Make sure they show up under "my reservations"
- Execute some test queries under "all reservations"
- Make sure "room info" is displaying correctly

2018-02-06 01:33 UTC, RobertEng requested changes

2018-02-06 01:33 UTC, RobertEng commented on donut/modules/rooms/templates/mine-iframe.html
> +							</p>
Probably want to allow people to delete their reservations here.

2018-02-06 01:33 UTC, RobertEng commented on donut/modules/rooms/helpers.py
> +
if its not too difficult, return success boolean. or do error checking of some kind.

2018-02-06 01:33 UTC, RobertEng commented on donut/modules/rooms/helpers.py
> +
again if its not too difficult, return success boolean

2018-02-06 01:33 UTC, RobertEng commented on donut/modules/rooms/routes.py
> +
should be POST request to "/1/reservation"

2018-02-06 01:33 UTC, RobertEng commented on donut/modules/rooms/routes.py
> +@blueprint.route("/reservation/<int:id>", methods=["GET"])
/1/

2018-02-06 01:33 UTC, RobertEng commented on donut/modules/rooms/routes.py
> +@blueprint.route("/reservation/<int:id>", methods=["DELETE"])
/1/

2018-02-06 01:33 UTC, RobertEng commented on sql/rooms.sql
> +	id INT NOT NULL AUTO_INCREMENT,
rename this room_id

2018-02-06 01:33 UTC, RobertEng commented on sql/rooms.sql
> +	id INT NOT NULL AUTO_INCREMENT,
rename this reservation_id

2018-02-06 02:10 UTC, calebsander commented
Alright, I addressed all the issues except for adding success information because I don't want to suppress an error report

2018-02-09 00:02 UTC, RobertEng commented
lgtm

2018-02-09 00:02 UTC, RobertEng approved these changes

2018-02-09 00:06 UTC, merged