Groups
ASCIT/donut pull request #74
Opened 2018-05-08 00:02 UTC by rlin0

### Summary
-  Endpoint for get position holders and deleted group_id from position holders

2018-05-08 00:11 UTC, majesticfish commented on donut/modules/groups/helpers.py
> +def create_position_holder(group_id, pos_id, user_id, start_date, end_date):
Try adding a test for this function

2018-05-08 00:12 UTC, majesticfish commented on donut/modules/groups/routes.py
> +        else:
Don't actually need this else

2018-05-08 00:13 UTC, majesticfish requested changes
Preferably create a test function to test the create_position_holder method.

2018-05-08 00:13 UTC, majesticfish commented on donut/modules/groups/helpers.py
> +        cursor.execute(s, (pos_id, user_id, start_date,
also run 'make lint'

2018-05-10 07:24 UTC, calebsander requested changes
What Sean said, and some small other suggested edits

2018-05-10 07:24 UTC, calebsander commented on donut/modules/groups/helpers.py
> +# TODO: Implement this helper function
Remove `TODO`

2018-05-10 07:24 UTC, calebsander commented on donut/modules/groups/routes.py
> +# TODO: Modify this end point to have both POST and GET methods
Remove `TODO`

2018-05-10 07:24 UTC, calebsander commented on donut/modules/groups/routes.py
> +@blueprint.route("/1/positions/<int:pos_id>/", methods=["POST", "GET"])
`POST` and `GET` handlers should go in different functions if they don't share any code:
````python
@blueprint.route("/1/positions/<int:pos_id>/", methods=["GET"])
def get_pos_holders(pos_id):
    return jsonify(helpers.get_position_holders(pos_id))

@blueprint.route("/1/positions/<int:pos_id>/", methods=["POST"])
def add_pos_holder(pos_id):
    # your code...
````

2018-05-10 07:24 UTC, calebsander commented on donut/modules/groups/routes.py
> +            helpers.create_position_holder(int(pos_id), int(form["user_id"]),
`pos_id` should already be an `int`, no?

2018-05-15 01:22 UTC, calebsander commented on donut/modules/groups/helpers.py
> +# TODO: Implement this helper function
Remove `TODO`

2018-06-04 23:13 UTC, majesticfish approved these changes

2018-06-04 23:19 UTC, merged