Feedback
ASCIT/donut pull request #96
Opened 2019-05-07 00:58 UTC by rlin0

### Summary
- combined arc and bod into 1 feedback module

2019-06-03 23:08 UTC, koivyr commented on donut/modules/feedback/routes.py
> +    if group not in Groups:
You repeat a lot of the status checking conditions-- maybe roll them into a helper function?

2019-06-03 23:08 UTC, koivyr commented on donut/modules/feedback/routes.py
> +        return flask.render_template("404.html")
can just do ```flask.abort(404)``` here and everywhere else

2019-06-03 23:08 UTC, koivyr commented on donut/modules/feedback/routes.py
> +        flask.abort(403)
```return flask.abort(403)``` here and everywhere else.

2019-06-03 23:08 UTC, koivyr commented on donut/modules/feedback/email_templates.py
> +We have received BoD feedback that you're subscribed to.
Change BoD to ```{}```

2019-06-05 23:30 UTC, rlin0 commented on donut/modules/feedback/routes.py
> +    if group not in Groups:
They're different permissions though. I feel like it's not worth?

2019-07-14 20:18 UTC, calebsander requested changes
Looks fine; just a few comments relating to merging with other recent changes

2019-07-14 20:18 UTC, calebsander commented on donut/modules/feedback/permissions.py
> +    SUMMARY = 12
I think permission 12 is now used for masquerading, so we should pick a different number. Are you sure these are all in the database? I thought Logan looked for an unused permission number

2019-07-14 20:18 UTC, calebsander commented on donut/templates/includes/header.html
> +                            <li><a href="#">Documents</a></li>
Documents link is duplicated

2019-10-23 23:35 UTC, koivyr submitted a review, later dismissed
Just do Caleb's feedback^

2019-10-31 00:04 UTC, calebsander approved these changes

2019-10-31 00:04 UTC, merged